export class ApplicationFields {
    constructor(public Navigation       : object,
                public Id               : string,
                public DisplayName      : string,
                public Entity           : string,
                public Icon             : string,
                public SubEntities      : object,
                public Router           : string,
                public InputCard        : object,
                public CardTitle        : string,
                public CardSubTitle     : string,
                public Controls         : object,
                public ModelName        : string,
                public ControlType      : string,
                public Options          : object,
                public PlaceHolder      : string,
                public ToolTip          : string,
                public RequiredLevel    : boolean,
                public Visible          : boolean,
                public ShowLabel        : boolean,
                public Disabled         : boolean,
                public QueryParameters  : string,     
                ) {}
}